# Generated by Django 4.2 on 2023-10-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(max_length=50)),
                ('to_city', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=60)),
                ('moblie', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('blood_group', models.CharField(max_length=50)),
                ('birth', models.CharField(max_length=50)),
            ],
        ),
    ]
